/**
 * Registre des outils du nouvel Atelier (UX2, UX4 ; cahier des charges §5.8) : famille, synonymes (français et
 * termes d'autres logiciels), aide située (une phrase + un exemple), conditions d'activation, raccourci, niveau
 * d'affichage à partir duquel l'outil est proposé. La palette cherche dans tout cela ; la barre affiche les
 * favoris et les outils du niveau d'affichage courant.
 */
import type { NiveauAffichage } from "./etat-ui";

export type Famille = "creer" | "modifier" | "connecter" | "analyser" | "documenter" | "partager" | "naviguer";

export interface Outil {
  id: string;
  libelle: string;
  famille: Famille;
  /** Pictogramme texte (pas d'image inventée). */
  picto: string;
  synonymes: string[];
  aide: string;
  exemple: string;
  /** Condition d'activation (lisible) ; `null` = toujours. */
  condition: "selection" | "selection-mur" | "selection-ligne" | "niveau" | null;
  raccourci: string | null;
  affichage: NiveauAffichage;
  /** Entrée DA de la fiche de capacité. */
  fiche: string;
  /** Ontologie activable (P2-2) qui porte l'outil ; absent : socle. L'outil n'est proposé qu'une fois l'ontologie activée. */
  ontologie?: "mechanical" | "structure" | "timber" | "sheetmetal" | "mep";
  /** L'outil a son panneau dans l'inspecteur (saisie puis validation), même sans sélection préalable (P2-6, socle). */
  panneau?: true;
}

const O = (o: Outil): Outil => o;

export const OUTILS: readonly Outil[] = [
  O({ id: "selection", libelle: "Sélection", famille: "naviguer", picto: "↖", synonymes: ["select", "pick", "flèche", "choisir"], aide: "Cliquez un objet ; glissez pour un cadre ; Alt + glisser pour un lasso ; Maj pour ajouter ; en 3D, glissez une flèche pour déplacer la sélection.", exemple: "Cliquer un mur, puis modifier son épaisseur dans l'inspecteur.", condition: null, raccourci: "v", affichage: "essentiel", fiche: "DA-02-15" }),
  O({ id: "lasso", libelle: "Lasso", famille: "naviguer", picto: "➰", synonymes: ["lasso", "main levée", "sélection libre", "entourer"], aide: "Glissez autour des objets : ceux entièrement entourés sont sélectionnés ; Maj pour ajouter à la sélection.", exemple: "Entourer les cloisons d'un plateau en forme de L.", condition: null, raccourci: null, affichage: "contextuel", fiche: "DA-02-15" }),
  O({ id: "naviguer", libelle: "Panoramique", famille: "naviguer", picto: "✋", synonymes: ["pan", "main", "déplacer la vue", "glisser la vue"], aide: "Glissez pour déplacer la vue ; la molette zoome ; Échap revient à l'outil précédent.", exemple: "Faire glisser le plan pour voir l'aile est.", condition: null, raccourci: "h", affichage: "contextuel", fiche: "DA-17-16" }),
  O({ id: "zoom", libelle: "Zoom", famille: "naviguer", picto: "🔍", synonymes: ["zoom", "loupe", "agrandir", "zoom fenêtre", "window zoom"], aide: "Cliquez pour rapprocher (× 2) ; Maj ou Alt + clic pour éloigner ; glissez un cadre pour zoomer dessus.", exemple: "Encadrer la cage d'escalier pour la voir en grand.", condition: null, raccourci: null, affichage: "contextuel", fiche: "DA-17-16" }),
  O({ id: "zoom-etendu", libelle: "Zoom étendu", famille: "naviguer", picto: "⤢", synonymes: ["zoom extents", "tout voir", "cadrer", "ajuster à la fenêtre"], aide: "Cadre tout le niveau dans la vue (touche 0).", exemple: "Revoir tout le plan après un zoom.", condition: null, raccourci: null, affichage: "contextuel", fiche: "DA-17-16" }),
  O({ id: "repere-saisie", libelle: "Repère de saisie", famille: "naviguer", picto: "⊾", synonymes: ["ucs", "scu", "repère", "repère local", "orienter la saisie", "axes"], aide: "Cliquez l'origine puis un point de l'axe x′ : saisies « dx;dy », repérage polaire et manipulateur suivent ce repère (pour vous seulement). « Repère global » dans la barre d'état le retire.", exemple: "Orienter la saisie le long d'une façade biaise.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-02-16" }),
  O({ id: "mur-courbe", libelle: "Mur courbe", famille: "creer", picto: "◠", synonymes: ["curved wall", "mur cintré", "mur en arc", "mur arrondi"], aide: "Cliquez le début, la fin, puis un point de l'arc (demi-cercle au plus) ; épaisseur et hauteur comme pour un mur.", exemple: "Mur cintré d'une abside.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-01" }),
  O({ id: "mur", libelle: "Mur", famille: "creer", picto: "▬", synonymes: ["wall", "cloison", "paroi", "tracer un mur"], aide: "Cliquez le début puis la fin de l'axe ; tapez une longueur pour la saisie de précision ; Entrée termine, Échap annule.", exemple: "Un mur de 4 m : cliquer, taper 4, Entrée.", condition: "niveau", raccourci: "m", affichage: "essentiel", fiche: "DA-07-01" }),
  O({ id: "porte", libelle: "Porte", famille: "creer", picto: "◩", synonymes: ["door", "ouverture", "passage"], aide: "Cliquez sur un mur pour y poser la porte ; largeur et hauteur dans l'inspecteur.", exemple: "Porte 0,90 × 2,10 m au tiers du mur.", condition: "niveau", raccourci: "p", affichage: "essentiel", fiche: "DA-07-02" }),
  O({ id: "fenetre", libelle: "Fenêtre", famille: "creer", picto: "▢", synonymes: ["window", "baie", "châssis"], aide: "Cliquez sur un mur pour y poser la fenêtre ; allège, largeur et hauteur dans l'inspecteur.", exemple: "Fenêtre 1,20 × 1,40 m, allège 0,90 m.", condition: "niveau", raccourci: "f", affichage: "essentiel", fiche: "DA-07-03" }),
  O({ id: "ouverture", libelle: "Ouverture", famille: "creer", picto: "▭", synonymes: ["opening", "réservation", "trémie murale", "baie libre"], aide: "Cliquez sur un mur pour y réserver une ouverture libre.", exemple: "Ouverture 1,00 × 2,10 m sans menuiserie.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-04" }),
  O({ id: "dalle", libelle: "Dalle", famille: "creer", picto: "▱", synonymes: ["slab", "plancher", "floor", "dalle béton"], aide: "Cliquez les sommets du contour ; cliquez le premier point ou Entrée pour fermer.", exemple: "Dalle de 0,25 m sur l'emprise du niveau.", condition: "niveau", raccourci: "d", affichage: "essentiel", fiche: "DA-07-06" }),
  O({ id: "toiture", libelle: "Toiture", famille: "creer", picto: "⌂", synonymes: ["roof", "toit", "couverture"], aide: "Cliquez les sommets du contour ; avec une pente, le premier côté est l'égout (monopente) ou parallèle au faîtage (bipente). Pente 0 : toiture plate.", exemple: "Toiture bipente à 30°, faîtage parallèle au premier côté.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-07" }),
  O({ id: "escalier-helicoidal", libelle: "Escalier hélicoïdal", famille: "creer", picto: "◎", synonymes: ["escalier en colimaçon", "colimaçon", "spiral", "hélice"], aide: "Renseignez rayon intérieur, balayage, hauteur, contremarches et épaisseur des marches ; cliquez le centre, puis le bord extérieur de la première marche.", exemple: "Colimaçon d'un tour, 16 marches.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-10" }),
  O({ id: "escalier-volees", libelle: "Escalier à volées", famille: "creer", picto: "⌐", synonymes: ["escalier en L", "escalier tournant", "palier", "volées", "quart tournant", "demi-tour"], aide: "Renseignez largeur, hauteur, contremarches et épaisseur des paliers ; cliquez le départ, chaque angle, l'arrivée, puis Entrée : une volée par tronçon, un palier carré à chaque angle.", exemple: "Escalier en L de 18 contremarches avec un palier.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-10" }),
  O({ id: "escalier-balance", libelle: "Escalier balancé", famille: "creer", picto: "↰", synonymes: ["balancement", "marches balancées", "escalier tournant sans palier", "quart tournant balancé", "winder"], aide: "Renseignez largeur, hauteur, contremarches, épaisseur des marches, ligne de foulée et marches balancées par tournant ; cliquez le départ, chaque angle, l'arrivée, puis Entrée : girons égaux sur la ligne de foulée, marches balancées dans les tournants.", exemple: "Quart tournant balancé de 14 marches, 4 balancées.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-10" }),
  O({ id: "escalier", libelle: "Escalier", famille: "creer", picto: "▤", synonymes: ["stair", "stairs", "volée", "marches"], aide: "Cliquez le départ puis l'arrivée de l'axe ; largeur, hauteur à franchir et niveau d'arrivée dans l'inspecteur.", exemple: "Escalier droit RDC → mezzanine, 1,20 m, 18 contremarches.", condition: "niveau", raccourci: "e", affichage: "essentiel", fiche: "DA-07-10" }),
  O({ id: "plancher", libelle: "Plancher", famille: "creer", picto: "▤", synonymes: ["floor", "sol", "plancher du niveau", "dalle d'étage"], aide: "Choisissez la ligne de rive et l'épaisseur, puis cliquez dans le contour proposé (pointillés) : le plancher est créé avec ses trémies d'escalier.", exemple: "Créer le plancher du niveau actif, rive sur la face extérieure des murs.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-05" }),
  O({ id: "piece", libelle: "Pièce", famille: "creer", picto: "◫", synonymes: ["room", "local", "espace", "zone", "surface"], aide: "Cliquez dans une boucle fermée de murs : la pièce est proposée, puis créée avec son nom.", exemple: "Cliquer dans le bureau fermé par quatre murs → « Bureau 1 ».", condition: "niveau", raccourci: "r", affichage: "essentiel", fiche: "DA-07-15" }),
  O({ id: "espace", libelle: "Espace", famille: "creer", picto: "◧", synonymes: ["space", "espace déclaré", "programme"], aide: "Cliquez les sommets d'un espace déclaré (sans murs) ; nom et catégorie dans l'inspecteur.", exemple: "Espace « Terrasse » hors enveloppe.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-16" }),
  O({ id: "zone", libelle: "Zone", famille: "creer", picto: "⬚", synonymes: ["zone", "secteur", "noyau"], aide: "Cliquez les sommets de la zone ; elle contient les pièces qu'elle recouvre.", exemple: "Zone « Noyau technique ».", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-17" }),
  O({ id: "poteau", libelle: "Poteau", famille: "creer", picto: "▣", synonymes: ["column", "colonne", "pilier", "post"], aide: "Cliquez l'emplacement ; section et hauteur dans l'inspecteur.", exemple: "Poteau 0,30 × 0,30 m.", condition: "niveau", raccourci: "o", affichage: "contextuel", fiche: "DA-03-13" }),
  O({ id: "solide", libelle: "Solide", famille: "creer", picto: "⬒", synonymes: ["extrude", "extrusion", "volume", "bloc", "push"], aide: "Cliquez les sommets du contour, puis la hauteur dans l'inspecteur : un solide générique est extrudé.", exemple: "Un comptoir de 1,10 m de haut.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-04-01" }),
  O({ id: "solide-exact", libelle: "Solide exact", famille: "creer", picto: "⬢", synonymes: ["révolution", "revolve", "balayage", "sweep", "lissage", "loft", "booléen", "boolean", "trou", "hole", "coque", "shell", "surface", "nappe", "patch", "congé", "fillet", "arrondi", "NURBS", "brep", "occt", "noyau exact"], aide: "Choisissez l'opération (révolution, balayage, lissage, booléen, trou, coque, surface, patch, congé), sélectionnez les esquisses ou solides, puis Aperçu et Créer dans l'inspecteur ; le serveur recalcule avec le même noyau.", exemple: "Révolution d'un rectangle de 20 cm autour d'une ligne : un fût.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-04-11" }),
  O({ id: "piece-mecanique", libelle: "Pièce mécanique", famille: "creer", picto: "⚙", synonymes: ["pièce", "part", "part design", "composant mécanique", "mécanique", "usinage"], aide: "Sélectionnez un ou plusieurs solides : chacun devient une pièce (géométrie copiée de sa source) posée dans l'assemblage choisi ; fixe pour le bâti.", exemple: "Le caisson d'une centrale de traitement d'air depuis son solide exact.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-10-01", ontologie: "mechanical" }),
  O({ id: "assemblage", libelle: "Assemblage", famille: "connecter", picto: "⛓", synonymes: ["assembly", "assemblage", "mécanisme", "machine", "ensemble mécanique"], aide: "Nommez l'assemblage : il porte un repère, ses pièces (celles sélectionnées y entrent) et leurs liaisons ; numérotation et nomenclature dans sa fiche.", exemple: "Assemblage « CTA » avec socle, caisson, ventilateur et panneau.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-10-06", ontologie: "mechanical" }),
  O({ id: "poutre", libelle: "Élément de structure", famille: "creer", picto: "⌶", synonymes: ["poutre", "beam", "structural member", "contreventement", "tirant", "panne", "chevron", "longrine", "profilé", "IPE", "HEA", "charpente"], aide: "Sélectionnez deux poteaux ou une ligne, ou saisissez les extrémités ; la section est saisie en millimètres ou tirée d'un catalogue sourcé du projet.", exemple: "Poutre IPE 200 entre les poteaux A1 et B1.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-08-01", ontologie: "structure" }),
  O({ id: "trame-structure", libelle: "Trame structurale", famille: "creer", picto: "⊞", synonymes: ["trame structurale", "trame de poteaux", "grid", "structural grid", "files", "rangs", "ossature", "framing", "frame design", "génération"], aide: "Origine, orientation, files et rangs ; la génération des poteaux et des poutres se demande dans la fiche de la trame, après aperçu.", exemple: "Trame A–C × 1–2, entraxes 6 m et 5 m, puis génération en acier.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-08-04", ontologie: "structure" }),
  O({ id: "plaque", libelle: "Plaque", famille: "creer", picto: "▰", synonymes: ["plaque", "plate", "platine", "tôle structurale", "goussets"], aide: "Sélectionnez une esquisse fermée ou une dalle : son contour devient une plaque à l'épaisseur saisie.", exemple: "Platine 500 × 500 × 20 mm en tête de poteau.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-08-09", ontologie: "structure" }),
  O({ id: "assemblage-structurel", libelle: "Assemblage structurel", famille: "connecter", picto: "⊟", synonymes: ["assemblage", "connection", "platine d'about", "gousset", "boulons", "bolts", "éclisse", "steel connection"], aide: "Sélectionnez les éléments reliés : platine et boulons paramétriques (géométrie seulement, aucune vérification).", exemple: "Platine d'about 200 × 300 × 15 mm, 2 × 2 boulons M16.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-08-12", ontologie: "structure" }),
  O({ id: "soudure", libelle: "Soudure", famille: "connecter", picto: "⌇", synonymes: ["soudure", "weld", "cordon", "weldment", "assemblage soudé"], aide: "Sélectionnez deux éléments (Maj + clic) : type, gorge et longueur de cordon saisis ; les éléments reliés forment un assemblage soudé.", exemple: "Soudure d'angle gorge 5 mm, 300 mm, entre poutre et platine.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-08-11", ontologie: "structure" }),
  O({ id: "armature", libelle: "Armature", famille: "creer", picto: "≡", synonymes: ["armature", "ferraillage", "rebar", "reinforcement", "cadre", "étrier", "barre", "HA"], aide: "Sélectionnez l'hôte en béton (poutre, dalle, plaque, poteau) ou une esquisse pour le tracé ; diamètre, nombre et espacement saisis.", exemple: "5 HA 12 sur 6 m dans la poutre B1, espacement 150 mm.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-08-14", ontologie: "structure" }),
  O({ id: "coulage", libelle: "Coulage", famille: "connecter", picto: "⬓", synonymes: ["coulage", "pour", "concrete pour", "lot", "préfabriqué", "precast", "phase de bétonnage"], aide: "Les éléments en béton sélectionnés forment un coulage (ou un lot préfabriqué) ; ses quantités viennent des éléments.", exemple: "Coulage 1 : poteaux et poutres du rez-de-chaussée.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-08-16", ontologie: "structure" }),
  O({ id: "element-bois", libelle: "Élément bois", famille: "creer", picto: "⌸", synonymes: ["bois", "timber", "madrier", "chevron", "panne", "solive", "montant", "lisse", "poutre bois", "charpente bois"], aide: "Deux poteaux, une ligne ou des extrémités saisies ; section en millimètres (essence et classe déclarées) ou désignation d'un catalogue sourcé.", exemple: "Panne 75 × 225 en épicéa C24 (déclaré).", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-09-01", ontologie: "timber" }),
  O({ id: "ossature", libelle: "Ossature bois", famille: "creer", picto: "⌗", synonymes: ["ossature", "mur à ossature", "timber frame", "stud wall", "charpente", "chevrons", "roof framing", "automatique"], aide: "Sélectionnez un mur ou une toiture en pente : l'ossature se décrit (entraxe, sections) puis se génère depuis sa fiche après aperçu.", exemple: "Mur à ossature 45 × 145 à 600 mm, linteaux aux baies.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-09-07", ontologie: "timber" }),
  O({ id: "panneau-clt", libelle: "Panneau CLT", famille: "creer", picto: "▥", synonymes: ["CLT", "bois lamellé-croisé", "panneau massif", "cross laminated"], aide: "Sélectionnez un mur ou une ligne (panneau vertical) ou une esquisse fermée / dalle (plancher) ; épaisseur et couches saisies.", exemple: "Panneau CLT 5 couches, 100 mm, sur le mur nord.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-09-03", ontologie: "timber" }),
  O({ id: "assemblage-bois", libelle: "Assemblage bois", famille: "connecter", picto: "⌲", synonymes: ["tenon", "mortaise", "mi-bois", "sabot", "équerre", "ferrure", "quincaillerie", "connecteur bois", "wood connection"], aide: "Sélectionnez deux pièces (Maj + clic) : type bois–bois ou bois–métal, ferrure et quincaillerie déclarées avec leur source.", exemple: "Sabot entre solive et poutre, 20 pointes annelées.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-09-04", ontologie: "timber" }),
  O({ id: "tole", libelle: "Tôle pliée", famille: "creer", picto: "⌐", synonymes: ["tôle", "sheet metal", "pli", "pliage", "développé", "flat pattern", "capot", "carter"], aide: "Face de base, épaisseur, rayon, plis par bord ; paramètres de pliage depuis une table sourcée ou un facteur K déclaré — le développé se lit dans la fiche.", exemple: "Capot 400 × 300 × 2 mm, deux plis à 90°.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-11-01", ontologie: "sheetmetal" }),
  O({ id: "segment-reseau", libelle: "Segment de réseau", famille: "creer", picto: "⟿", synonymes: ["réseau", "tuyau", "pipe", "gaine", "duct", "chemin de câbles", "cable tray", "conduit", "routage", "routing", "CVC", "HVAC", "plomberie", "MEP"], aide: "Sélectionnez une ligne ou une polyligne d'esquisse, ou saisissez les sommets « x ; y ; z » ; section saisie ou de catalogue sourcé, fluide déclaré ; plusieurs sommets sont routés avec un coude à chaque angle.", exemple: "Tuyau d'eau froide Ø 60,3 le long d'une polyligne, coudes de 100 mm.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-12-04", ontologie: "mep" }),
  O({ id: "raccord-reseau", libelle: "Raccord", famille: "connecter", picto: "⌐", synonymes: ["raccord", "fitting", "coude", "elbow", "té", "tee", "réduction", "reducer", "manchon", "bouchon"], aide: "Type, système, section, longueur des bras et pose : les ports sont au bout des bras ; connectez-les ensuite aux segments.", exemple: "Coude Ø 60,3 à 90°, bras de 100 mm.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-12-08", ontologie: "mep" }),
  O({ id: "vanne", libelle: "Vanne", famille: "connecter", picto: "⋈", synonymes: ["vanne", "valve", "robinet", "clapet", "anti-retour", "soupape", "trois voies"], aide: "Type (arrêt, réglage, anti-retour, sécurité, trois voies), section, longueur face à face et pose ; les faces sont ses ports.", exemple: "Clapet anti-retour Ø 60,3, 200 mm face à face.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-12-09", ontologie: "mep" }),
  O({ id: "equipement-reseau", libelle: "Équipement de réseau", famille: "creer", picto: "▣", synonymes: ["équipement", "equipment", "pompe", "pump", "ventilateur", "fan", "centrale", "CTA", "AHU", "chaudière", "boiler", "ballon", "radiateur", "bouche"], aide: "Boîte posée (L × l × h, altitude, angle), type déclaré, catégorie IFC et ports un par un (système, section, sens, fluide).", exemple: "Pompe P1 600 × 400 × 600 mm, aspiration et refoulement Ø 60,3.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-12-10", ontologie: "mep" }),
  O({ id: "support-reseau", libelle: "Support de réseau", famille: "creer", picto: "⊥", synonymes: ["support", "hanger", "collier", "suspente", "rail", "console", "fixation"], aide: "Sélectionnez un segment : collier, suspente (longueur déclarée), rail ou console posé à une fraction de son tracé.", exemple: "Suspente de 300 mm au milieu de la gaine de soufflage.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-12-12", ontologie: "mep" }),
  O({ id: "connexion-reseau", libelle: "Connexion de réseau", famille: "connecter", picto: "⇔", synonymes: ["connecter", "connexion", "connect", "port", "connectivité", "raccorder"], aide: "Sélectionnez deux objets de réseau (Maj + clic), choisissez leurs ports : la compatibilité (système, section, fluide, sens, coïncidence) est lue avant d'agir ; ou connectez d'un coup tous les ports coïncidents.", exemple: "Relier le tuyau EF 1 au port d'aspiration de la pompe.", condition: null, raccourci: null, affichage: "contextuel", fiche: "DA-12-01", ontologie: "mep" }),
  O({ id: "specification-reseau", libelle: "Spécification de réseau", famille: "documenter", picto: "≡", synonymes: ["spécification", "specification", "spec", "classe de tuyauterie", "piping class", "catalogue", "catalog"], aide: "Système, fluide, matériau, catalogue sourcé et désignations admises : les objets qui la suivent y prennent leur section ; catalogues livrés vides, à importer (gabarit tubes-raccords.csv).", exemple: "Spécification « Eau froide acier » sur le catalogue tubes T, DN 50 admis.", condition: null, raccourci: null, affichage: "contextuel", fiche: "DA-12-17", ontologie: "mep" }),
  // Bâtiment P2 et surfaces libres (P2-6, socle `building.architecture` et `drawing`) : panneaux dans l'inspecteur.
  O({ id: "plafond", libelle: "Plafond", famille: "creer", picto: "⬒", synonymes: ["plafond", "ceiling", "faux plafond", "suspendu", "sous-face"], aide: "Sélectionnez une esquisse fermée, une dalle ou une pièce (son contour) ou gardez le rectangle ; hauteur sous plafond, épaisseur, suspendu ou non.", exemple: "Faux plafond à 2,50 m sur la pièce Bureau.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-08", panneau: true }),
  O({ id: "coque", libelle: "Coque", famille: "creer", picto: "◠", synonymes: ["coque", "shell roof", "dôme", "voûte", "voile mince", "paraboloïde"], aide: "Dôme paraboloïdal déclaré sur un contour : flèche au centre, épaisseur, base. Géométrie seulement.", exemple: "Coque de 1,5 m de flèche sur un carré de 10 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-09", panneau: true }),
  O({ id: "rampe", libelle: "Rampe", famille: "creer", picto: "⟋", synonymes: ["rampe", "ramp", "pente", "plan incliné", "accès PMR"], aide: "Axe a → b (ligne, mur ou saisie), largeur, hauteur à franchir, épaisseur ; la pente est dérivée et affichée, jamais comparée à une règle.", exemple: "Rampe de 6 m, 1,40 m de large, 0,50 m à franchir.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-11", panneau: true }),
  O({ id: "echelle", libelle: "Échelle", famille: "creer", picto: "⫴", synonymes: ["échelle", "ladder", "échelle à crinoline", "barreaux", "accès toiture"], aide: "Pied en a, appui vers b ; hauteur, largeur, entraxe des barreaux déclaré, crinoline à partir d'une hauteur.", exemple: "Échelle de 4 m, crinoline à partir de 2,20 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-13", panneau: true }),
  O({ id: "mur-rideau", libelle: "Mur-rideau", famille: "creer", picto: "▦", synonymes: ["mur-rideau", "mur rideau", "curtain wall", "façade vitrée", "façade légère", "montants", "traverses", "VEC"], aide: "Axe a → b, hauteur, entraxes des montants et des traverses, profils, vitrage : la façade est dessinée depuis ces seules valeurs.", exemple: "Façade de 6 m × 3 m, trame 1,50 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-14", panneau: true }),
  O({ id: "terrain", libelle: "Terrain", famille: "creer", picto: "⛰", synonymes: ["terrain", "terrain naturel", "TN", "topographie", "topo", "MNT", "semis de points", "courbes de niveau", "site"], aide: "Points relevés « x ; y ; z », triangulés (Delaunay) ; aucune altitude n'est inventée hors du semis ; source du relevé déclarée.", exemple: "Quatre coins relevés par le géomètre et un point haut.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-18", panneau: true }),
  O({ id: "reservation", libelle: "Réservation", famille: "connecter", picto: "⊡", synonymes: ["réservation", "réserve", "trémie de réseau", "percement", "passage de gaine", "opening for services", "provision"], aide: "Sélectionnez l'hôte (mur, dalle, poteau) et le réseau concerné ; emprise, altitude, hauteur, statut. Accordée, elle exempte la collision couverte.", exemple: "Réservation 60 × 40 cm accordée dans le mur pour la gaine de soufflage.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-17-14", panneau: true }),
  O({ id: "installation-chantier", libelle: "Installation de chantier", famille: "creer", picto: "⛟", synonymes: ["chantier", "installation de chantier", "grue", "base vie", "cantonnement", "stockage", "clôture de chantier", "site logistics", "planning chantier", "phasage"], aide: "Emprise (esquisse fermée ou rectangle), type, hauteur, dates et phase de chantier déclarées ; hors métrés de l'ouvrage.", exemple: "Grue G1 de 40 m, du 1er mars au 30 novembre, phase gros œuvre.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-23", panneau: true }),
  O({ id: "surface-libre", libelle: "Surface libre", famille: "creer", picto: "◍", synonymes: ["surface libre", "forme libre", "SubD", "subdivision", "maillage", "mesh", "morphing", "sculpter", "freeform", "convertir en maillage"], aide: "Maillage de contrôle subdivisé (Loop) ; déplacez ses sommets dans la fiche (morphing) ; un objet sélectionné se convertit explicitement, son maillage devenant le maillage de contrôle.", exemple: "Pyramide à cinq sommets subdivisée deux fois, sommet relevé de 0,5 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-03-03", panneau: true }),
  O({ id: "liaison", libelle: "Liaison", famille: "connecter", picto: "⟟", synonymes: ["mate", "joint", "pivot", "glissière", "encastrement", "rotule", "contrainte d'assemblage", "cinématique"], aide: "Sélectionnez deux pièces du même assemblage (Maj + clic), choisissez le type (pivot, glissière, encastrement…), les références et la valeur pilotée : le solveur pose les pièces et dit son diagnostic.", exemple: "Pivot ventilateur / caisson, angle 45°.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-10-08", ontologie: "mechanical" }),
  O({ id: "ligne", libelle: "Ligne", famille: "creer", picto: "╱", synonymes: ["line", "segment", "trait", "pen"], aide: "Cliquez deux points ; Maj contraint à l'orthogonal.", exemple: "Ligne de 3 m à 45°.", condition: "niveau", raccourci: "l", affichage: "contextuel", fiche: "DA-01-02" }),
  O({ id: "garde-corps", libelle: "Garde-corps", famille: "creer", picto: "⫴", synonymes: ["railing", "guardrail", "rambarde", "balustrade", "main courante"], aide: "Cliquez les points du garde-corps ; Entrée termine. La hauteur est celle saisie dans l'inspecteur (valeur de l'outil, pas une exigence réglementaire).", exemple: "Garde-corps de mezzanine sur trois côtés.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "lot 5 · objets reportés" }),
  O({ id: "bloc", libelle: "Placer un bloc", famille: "creer", picto: "❖", synonymes: ["block", "insert", "symbole", "composant", "component", "bibliothèque", "mobilier"], aide: "Choisissez le bloc ou le composant dans l'inspecteur, puis cliquez son point de base sur le plan.", exemple: "Placer trois tables « Mobilier · Table 6 places ».", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-05-06" }),
  O({ id: "polyligne", libelle: "Polyligne", famille: "creer", picto: "⌇", synonymes: ["polyline", "chaîne", "tracé"], aide: "Cliquez les points successifs ; Entrée termine, cliquer le premier point ferme en polygone.", exemple: "Contour d'un massif en cinq points.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-02" }),
  O({ id: "rectangle", libelle: "Rectangle", famille: "creer", picto: "▭", synonymes: ["rect", "carré", "square", "box"], aide: "Cliquez deux coins opposés.", exemple: "Rectangle 2 × 3 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-04" }),
  O({ id: "cercle", libelle: "Cercle", famille: "creer", picto: "○", synonymes: ["circle", "rond", "disque"], aide: "Cliquez le centre puis un point du cercle.", exemple: "Cercle de rayon 1,50 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-03" }),
  O({ id: "arc", libelle: "Arc", famille: "creer", picto: "◠", synonymes: ["arc", "courbe"], aide: "Cliquez le centre, le début puis la fin de l'arc.", exemple: "Arc de 90° de rayon 2 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-03" }),
  O({ id: "polygone-regulier", libelle: "Polygone régulier", famille: "creer", picto: "⬢", synonymes: ["polygon regular", "hexagone", "pentagone", "octogone"], aide: "Renseignez le nombre de côtés, puis cliquez le centre et un sommet.", exemple: "Hexagone de 2 m de rayon.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-02" }),
  O({ id: "cercle-3-points", libelle: "Cercle par 3 points", famille: "creer", picto: "◌", synonymes: ["circle 3 points", "cercle trois points", "cercle circonscrit"], aide: "Cliquez trois points du cercle.", exemple: "Cercle passant par trois poteaux.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-03" }),
  O({ id: "rectangle-centre", libelle: "Rectangle par centre", famille: "creer", picto: "⊡", synonymes: ["rectangle centre", "rectangle centré"], aide: "Cliquez le centre puis un coin.", exemple: "Table 1,6 × 0,8 m centrée sur un axe.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-04" }),
  O({ id: "rectangle-3-points", libelle: "Rectangle par 3 points", famille: "creer", picto: "▱", synonymes: ["rectangle incliné", "rectangle tourné", "rectangle 3 points"], aide: "Cliquez les deux extrémités d'un côté, puis un point qui donne la largeur.", exemple: "Terrasse alignée sur un mur oblique.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-04" }),
  O({ id: "cercle-2-points", libelle: "Cercle par 2 points", famille: "creer", picto: "⊖", synonymes: ["cercle diamètre", "circle 2 points"], aide: "Cliquez les deux extrémités d'un diamètre.", exemple: "Cercle entre deux poteaux.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-03" }),
  O({ id: "ellipse", libelle: "Ellipse", famille: "creer", picto: "⬭", synonymes: ["ellipse", "ovale", "oval"], aide: "Cliquez le centre, l'extrémité d'un axe, puis un point qui donne l'autre demi-axe.", exemple: "Table ovale 2,4 × 1,2 m.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-03" }),
  O({ id: "contour", libelle: "Contour détecté", famille: "creer", picto: "⬚", synonymes: ["détecter contour", "boundary", "contour fermé", "hachurer zone"], aide: "Cliquez à l'intérieur d'une région fermée par des lignes d'esquisse : un polygone (ou une hachure) en reprend le contour.", exemple: "Hachurer une zone délimitée par des lignes.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-02" }),
  O({ id: "trame", libelle: "Trame d'axes", famille: "creer", picto: "#", synonymes: ["grille d'axes", "axes numérotés", "grid", "trame structurelle"], aide: "Renseignez les entraxes, puis cliquez l'origine de la trame.", exemple: "Trame 3 × 5,40 m en x, 2 × 6 m en y.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-10" }),
  O({ id: "arc-tangent", libelle: "Arc tangent", famille: "creer", picto: "⤻", synonymes: ["tangent arc", "arc tangent", "prolonger en arc", "continuer en courbe"], aide: "Cliquez près de l'extrémité d'une ligne, d'une polyligne ouverte ou d'un arc, puis la fin de l'arc : il part dans le prolongement exact.", exemple: "Arrondir le bout d'une allée.", condition: "niveau", raccourci: null, affichage: "complet", fiche: "DA-01-03" }),
  O({ id: "gomme", libelle: "Gomme", famille: "modifier", picto: "⌫", synonymes: ["eraser", "effacer", "gommer", "effacement partiel"], aide: "Glissez à travers des traits d'esquisse : ceux traversés sont supprimés en un seul lot ; Alt : effacement partiel, seule la portion entre deux traits voisins disparaît (les esquisses verrouillées restent ; murs et autres objets ne sont jamais gommés).", exemple: "Effacer les traits de construction d'un croquis.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-06" }),
  O({ id: "main-levee", libelle: "Main levée", famille: "creer", picto: "✎", synonymes: ["freehand", "croquis", "crayon", "dessin libre", "stylet"], aide: "Glissez pour dessiner (souris, stylet ou doigt) : le tracé est simplifié à la tolérance de l'outil et fermé s'il revient à son départ ; Alt au relâchement : courbe.", exemple: "Croquer le contour d'un jardin.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-06" }),
  O({ id: "polygone", libelle: "Polygone", famille: "creer", picto: "⬡", synonymes: ["polygon", "contour fermé"], aide: "Cliquez les sommets ; cliquer le premier point ferme.", exemple: "Hexagone régulier approché.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-04" }),
  O({ id: "spline", libelle: "Courbe", famille: "creer", picto: "∿", synonymes: ["spline", "curve", "courbe lisse", "bezier"], aide: "Cliquez les points de contrôle ; Entrée termine (Catmull-Rom).", exemple: "Courbe libre d'un cheminement.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-05" }),
  O({ id: "construction", libelle: "Ligne de construction", famille: "creer", picto: "┈", synonymes: ["construction", "axe", "centerline", "guide", "repère"], aide: "Cliquez deux points : la ligne sert aux accrochages, elle n'est pas dessinée dans les documents.", exemple: "Axe de symétrie du plateau.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-10" }),
  O({ id: "hachure", libelle: "Hachure", famille: "creer", picto: "▨", synonymes: ["hatch", "hachures", "remplissage", "motif"], aide: "Cliquez les sommets de la zone à hachurer ; motif dans l'inspecteur.", exemple: "Hachure béton sur une coupe.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-01-11" }),
  O({ id: "deplacer", libelle: "Déplacer", famille: "modifier", picto: "✥", synonymes: ["move", "translation", "glisser"], aide: "Sélectionnez, puis cliquez le point de départ et le point d'arrivée ; ou tapez dx, dy.", exemple: "Déplacer trois murs de 0,50 m vers le nord.", condition: "selection", raccourci: "g", affichage: "essentiel", fiche: "DA-02-01" }),
  O({ id: "copier", libelle: "Copier", famille: "modifier", picto: "⧉", synonymes: ["copy", "dupliquer", "clone"], aide: "Sélectionnez, puis cliquez le point de départ et le point d'arrivée de la copie ; un mur emmène des copies de ses ouvertures ; Alt : les pièces copiées prennent le code suivant.", exemple: "Copier un bureau type.", condition: "selection", raccourci: "c", affichage: "contextuel", fiche: "DA-02-02" }),
  O({ id: "tourner", libelle: "Tourner", famille: "modifier", picto: "⟳", synonymes: ["rotate", "rotation", "pivoter"], aide: "Sélectionnez, cliquez le centre, puis tapez l'angle ou cliquez la direction.", exemple: "Tourner de 90°.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-03" }),
  O({ id: "miroir", libelle: "Miroir", famille: "modifier", picto: "⇄", synonymes: ["mirror", "symétrie", "flip"], aide: "Sélectionnez, puis cliquez deux points de l'axe de symétrie ; Alt garde l'original.", exemple: "Symétriser l'aile est.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-04" }),
  O({ id: "echelle", libelle: "Échelle", famille: "modifier", picto: "⤢", synonymes: ["scale", "agrandir", "réduire", "homothétie"], aide: "Sélectionnez, cliquez le centre puis tapez le facteur, ou « fx;fy » pour des facteurs différents en x et en y ; les épaisseurs et hauteurs typées ne changent pas.", exemple: "× 1,5 sur une esquisse ; « 2;1 » l'étire en x seulement.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-05" }),
  O({ id: "etirer", libelle: "Étirer", famille: "modifier", picto: "↔", synonymes: ["stretch", "allonger", "prolonger une extrémité", "poignée"], aide: "Cliquez une extrémité de mur ou de ligne puis sa nouvelle position ; les ouvertures gardent leur distance à l'extrémité fixe, les murs joints suivent (Alt : mur seul).", exemple: "Allonger un mur de 4 à 6 m.", condition: "selection-mur", raccourci: null, affichage: "contextuel", fiche: "DA-02-06" }),
  O({ id: "etirer-fenetre", libelle: "Étirer par fenêtre", famille: "modifier", picto: "⤡", synonymes: ["stretch", "fenêtre polygonale", "lasso", "étirer plusieurs"], aide: "Entourez au lasso les sommets à étirer, puis cliquez le point de base et la destination : les objets entièrement entourés sont déplacés, les autres étirés (Échap : abandonner).", exemple: "Allonger d'un mètre l'aile est d'un plan : entourer son pignon, puis déplacer.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-02-06" }),
  O({ id: "ajuster", libelle: "Ajuster", famille: "modifier", picto: "⌐", synonymes: ["trim", "couper", "raccourcir jusqu'à"], aide: "Sélectionnez l'objet à raccourcir (mur, ligne, polyligne, spline), cliquez au besoin l'extrémité à couper, puis l'objet limite (axe, tracé, cercle ou contour). Forme fermée (dalle, pièce, polygone) : limite droite puis côté à garder.", exemple: "Ajuster une cloison sur le mur de façade.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-07" }),
  O({ id: "prolonger", libelle: "Prolonger", famille: "modifier", picto: "⊢", synonymes: ["extend", "allonger jusqu'à", "joindre"], aide: "Sélectionnez l'objet à prolonger (mur, ligne, polyligne, spline), cliquez au besoin l'extrémité à prolonger, puis l'objet limite (axe, tracé, cercle ou contour).", exemple: "Prolonger une cloison jusqu'au mur.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-08" }),
  O({ id: "decaler", libelle: "Décaler", famille: "modifier", picto: "∥", synonymes: ["offset", "parallèle", "décalage"], aide: "Sélectionnez des murs ou des lignes, tapez la distance, choisissez le côté ; Alt : angles arrondis (esquisses).", exemple: "Doublage à 0,10 m du mur.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-09" }),
  O({ id: "raccorder", libelle: "Raccorder", famille: "modifier", picto: "◜", synonymes: ["fillet", "congé", "arrondir", "raccord multiple"], aide: "Sélectionnez deux lignes d'esquisse (ou une ligne et un arc, ou deux arcs), ou plusieurs éléments jointifs pour arrondir tous leurs coins, tapez le rayon.", exemple: "Congé de 0,50 m.", condition: "selection-ligne", raccourci: null, affichage: "complet", fiche: "DA-02-10" }),
  O({ id: "chanfreiner", libelle: "Chanfreiner", famille: "modifier", picto: "◤", synonymes: ["chamfer", "chanfrein", "biseau"], aide: "Sélectionnez deux lignes d'esquisse (ou une ligne et un arc, ou deux arcs), ou plusieurs éléments jointifs pour chanfreiner tous leurs coins, tapez la distance (le long de chaque élément).", exemple: "Chanfrein de 0,20 m.", condition: "selection-ligne", raccourci: null, affichage: "complet", fiche: "DA-02-11" }),
  O({ id: "repeter", libelle: "Répéter", famille: "modifier", picto: "⋯", synonymes: ["array", "pattern", "trame de copies", "réseau de copies", "répétition", "dupliquer en série"], aide: "Sélectionnez, puis nombre et pas (dx, dy) ou centre et angle.", exemple: "Trame de poteaux tous les 6 m.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-12" }),
  O({ id: "reseau-trajet", libelle: "Réseau sur trajectoire", famille: "modifier", picto: "⤳", synonymes: ["path array", "réseau suivant une courbe", "répéter le long", "trajectoire"], aide: "Sélectionnez, renseignez le nombre de copies (ou un pas), cliquez la trajectoire (ligne, polyligne, courbe) puis le point de base de la sélection ; Alt : copies orientées le long du trajet.", exemple: "Huit bancs le long d'une allée courbe.", condition: "selection", raccourci: null, affichage: "complet", fiche: "DA-02-12" }),
  O({ id: "aligner", libelle: "Aligner", famille: "modifier", picto: "⇲", synonymes: ["align", "aligner sur", "caler"], aide: "Sélectionnez, puis cliquez un point source et sa destination, puis un second point source et sa direction de destination ; Alt garde l'original.", exemple: "Caler un mobilier sur un mur biais.", condition: "selection", raccourci: null, affichage: "complet", fiche: "DA-02-03" }),
  O({ id: "pousser", libelle: "Pousser / tirer", famille: "modifier", picto: "⇕", synonymes: ["push pull", "push/pull", "pousser tirer", "hauteur", "rehausser", "extruder"], aide: "En vue 3D : cliquez un mur, un poteau, un solide, une dalle ou une toiture et glissez vers le haut ou le bas ; la valeur s'affiche, le relâchement l'enregistre.", exemple: "Rehausser un mur de 2,50 à 3,00 m.", condition: null, raccourci: "u", affichage: "essentiel", fiche: "DA-04-07" }),
  O({ id: "extruder", libelle: "Extruder l'esquisse", famille: "creer", picto: "⬆", synonymes: ["extrude", "extrusion", "solidifier", "volume depuis esquisse"], aide: "Sélectionnez une esquisse fermée (rectangle, cercle, polygone) : elle devient un solide de la hauteur de l'outil.", exemple: "Un rectangle 2 × 1 m devient un bloc de 1,10 m.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-04-01" }),
  O({ id: "decomposer", libelle: "Décomposer", famille: "modifier", picto: "⊟", synonymes: ["explode", "éclater", "dissocier"], aide: "Sélectionnez des polylignes, polygones ou rectangles d'esquisse : ils deviennent des lignes.", exemple: "Décomposer un rectangle en quatre lignes.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-13" }),
  O({ id: "scinder", libelle: "Scinder", famille: "modifier", picto: "⫽", synonymes: ["split", "couper un mur", "diviser"], aide: "Cliquez un point sur l'axe d'un mur : deux murs, les ouvertures suivent, les cotes rattachées passent « à réparer ».", exemple: "Scinder un mur de 8 m au milieu.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-07-01" }),
  O({ id: "supprimer", libelle: "Supprimer", famille: "modifier", picto: "⌫", synonymes: ["delete", "erase", "effacer", "retirer"], aide: "Supprime la sélection ; un mur hébergeant des ouvertures demande confirmation.", exemple: "Sélectionner une cloison, puis Suppr.", condition: "selection", raccourci: "Delete", affichage: "essentiel", fiche: "DA-02-13" }),
  O({ id: "mesurer", libelle: "Mesurer", famille: "analyser", picto: "↔", synonymes: ["measure", "tape", "mètre", "distance"], aide: "Cliquez deux points : distance, dx, dy et angle s'affichent, rien n'est écrit.", exemple: "Vérifier un dégagement de 1,40 m.", condition: null, raccourci: "t", affichage: "essentiel", fiche: "DA-15-01" }),
  O({ id: "rapporteur", libelle: "Rapporteur", famille: "analyser", picto: "∠", synonymes: ["protractor", "angle", "mesurer un angle", "rapporteur"], aide: "Cliquez le sommet, un point du premier côté, puis le second côté (ou tapez l'angle puis Entrée) : l'angle s'affiche et une ligne de construction est posée ; Alt + clic mesure sans rien poser.", exemple: "Tracer un repère à 30° depuis l'angle de la façade.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-15-01" }),
  O({ id: "cotation", libelle: "Cotation", famille: "documenter", picto: "⟷", synonymes: ["dimension", "cote", "dim"], aide: "Cliquez deux points puis le décalage ; une cote cliquée sur une arête de mur s'y rattache.", exemple: "Cote de façade.", condition: "niveau", raccourci: "k", affichage: "essentiel", fiche: "DA-15-02" }),
  O({ id: "texte", libelle: "Texte", famille: "documenter", picto: "T", synonymes: ["text", "note", "annotation", "label"], aide: "Cliquez l'emplacement puis tapez le texte dans l'inspecteur.", exemple: "« Issue de secours ».", condition: "niveau", raccourci: null, affichage: "essentiel", fiche: "DA-15-04" }),
  O({ id: "etiquette", libelle: "Étiquette", famille: "documenter", picto: "⌸", synonymes: ["tag", "repère", "étiquette d'objet"], aide: "Cliquez un objet puis l'emplacement : l'étiquette porte son nom et le suit.", exemple: "Étiqueter chaque porte par son repère.", condition: "niveau", raccourci: null, affichage: "contextuel", fiche: "DA-15-06" }),
  O({ id: "calques", libelle: "Calques", famille: "naviguer", picto: "☰", synonymes: ["layers", "couches", "visibilité"], aide: "Visibilité et verrouillage des calques dans le navigateur ; affecter la sélection à un calque.", exemple: "Masquer « Mobilier ».", condition: null, raccourci: null, affichage: "essentiel", fiche: "DA-05-01" }),
  O({ id: "sommet", libelle: "Modifier un sommet", famille: "modifier", picto: "◇", synonymes: ["sommet", "point de contrôle", "vertex", "grip"], aide: "Sélectionnez un contour, cliquez un sommet puis sa nouvelle position ; les sommets confondus d'autres objets suivent (Alt : seul).", exemple: "Déplacer l'angle commun d'une dalle et d'une zone.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-14" }),
  O({ id: "chanfrein-sommet", libelle: "Chanfrein de sommet", famille: "modifier", picto: "⌔", synonymes: ["chanfrein sommet", "pan coupé", "coin coupé"], aide: "Sélectionnez un contour, renseignez la distance, puis cliquez le sommet à chanfreiner ; Alt : tous les sommets.", exemple: "Pan coupé de 1 m sur l'angle d'une dalle.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-11" }),
  O({ id: "axes-murs", libelle: "Axes des murs", famille: "creer", picto: "┼", synonymes: ["axe de mur", "ligne d'axe", "centerline"], aide: "Trace l'axe de chaque mur sélectionné en ligne de construction.", exemple: "Axes des murs porteurs pour une trame.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-01-10" }),
  O({ id: "scinder-piece", libelle: "Scinder une pièce", famille: "modifier", picto: "⫽", synonymes: ["diviser pièce", "couper pièce", "split room"], aide: "Sélectionnez une pièce, puis cliquez deux points d'une ligne qui la traverse.", exemple: "Séparer un séjour-cuisine en deux pièces.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-07-15" }),
  O({ id: "joindre", libelle: "Joindre", famille: "modifier", picto: "⛓", synonymes: ["join", "pedit", "relier", "fusionner lignes", "joindre murs", "angle de murs"], aide: "Joint des lignes et polylignes bout à bout en une polyligne (un polygone si la chaîne se referme) ; deux murs sélectionnés : jonction d'angle (chacun prolongé ou raccourci jusqu'à l'axe de l'autre).", exemple: "Joindre quatre lignes en un contour fermé.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-02-13" }),
  O({ id: "grouper", libelle: "Grouper", famille: "modifier", picto: "⧈", synonymes: ["group", "regrouper", "ensemble"], aide: "Groupe la sélection ; « Dissoudre » dans l'inspecteur.", exemple: "Grouper un bloc sanitaire.", condition: "selection", raccourci: null, affichage: "contextuel", fiche: "DA-05-05" }),
];

export const OUTILS_PAR_ID: Readonly<Record<string, Outil>> = Object.fromEntries(OUTILS.map((o) => [o.id, o]));

const ORDRE: Record<NiveauAffichage, number> = { essentiel: 0, contextuel: 1, complet: 2 };

export function outilsVisibles(affichage: NiveauAffichage): Outil[] {
  return OUTILS.filter((o) => ORDRE[o.affichage] <= ORDRE[affichage]);
}

/** Recherche de la palette : libellé, synonymes, famille, fiche ; sans accents ni casse. */
export function rechercherOutils(texte: string): Outil[] {
  const q = normaliser(texte);
  if (!q) return [...OUTILS];
  return OUTILS.map((o) => ({ o, score: score(o, q) }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || a.o.libelle.localeCompare(b.o.libelle, "fr"))
    .map((x) => x.o);
}

function score(o: Outil, q: string): number {
  const l = normaliser(o.libelle);
  if (l === q) return 100;
  // Un synonyme exact (« pan » pour Panoramique) prime sur un libellé qui commence par le mot (Panneau CLT).
  if (o.synonymes.some((s) => normaliser(s) === q)) return 90;
  if (l.startsWith(q)) return 80;
  if (l.includes(q)) return 50;
  if (o.synonymes.some((s) => normaliser(s).includes(q))) return 40;
  if (normaliser(o.aide).includes(q) || normaliser(o.fiche).includes(q) || normaliser(o.famille).includes(q)) return 10;
  return 0;
}

export const normaliser = (s: string): string => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().trim();

export const FAMILLES: Record<Famille, string> = { creer: "Créer", modifier: "Modifier", connecter: "Connecter", analyser: "Analyser", documenter: "Documenter", partager: "Partager", naviguer: "Naviguer" };
